export const INCREMENT_CART_COUNTER: string = "INCREMENT_CART_COUNTER"
export const DECREMENT_CART_COUNTER: string = "DECREMENT_CART_COUNTER"
export const ADD_CART_CONTENT: string = "ADD_CART_CONTENT"
export const DELETE_CART_CONTENT: string = "DELETE_CART_CONTENT"